#!/usr/bin/env python3
# Generate data for dp-caxpy (CAXPY: y = alpha*x + y). Outputs to ../data/data_${M}.h

import numpy as np
import torch
import argparse
import pathlib
import hjson

np.random.seed(42)
torch.manual_seed(42)

def array_to_cstr(a, fmt=float):
    out = "{"
    if isinstance(a, torch.Tensor):
        a = a.detach().cpu().numpy().flat
    elif isinstance(a, np.ndarray):
        a = a.flat
    for el in a:
        out += "{:.8f}, ".format(el) if fmt == float else "{}, ".format(el)
    return out[:-2] + "}"

def complex_tensor_to_cstr(t):
    if t.is_complex():
        flat = torch.view_as_real(t).flatten()
    else:
        flat = t.flatten()
    return array_to_cstr(flat, fmt=float)

def rand_complex(shape, dtype):
    return torch.complex(torch.randn(shape, dtype=dtype), torch.randn(shape, dtype=dtype))

def emit_caxpy(name, **kwargs):
    M = kwargs["M"]
    prec = kwargs["prec"]
    X, Y = kwargs["X"], kwargs["Y"]
    alpha, result = kwargs["alpha"], kwargs["result"]
    c_struct = "cdouble" if prec == 64 else "cfloat" if prec == 32 else "chalf"
    s = '#include "layer.h"\n\n'
    s += f"// Kernel: CAXPY (y = alpha * x + y), Precision: {prec}-bit\n"
    s += f"const int {name}_n = {M};\n\n"
    s += f"static {c_struct} {name}_alpha = {{{alpha.real.item()}, {alpha.imag.item()}}};\n\n"
    s += f"static {c_struct} {name}_x[{M}] __attribute__((section(\".data\"))) = " + complex_tensor_to_cstr(X) + ";\n"
    s += f"static {c_struct} {name}_y[{M}] __attribute__((section(\".data\"))) = " + complex_tensor_to_cstr(Y) + ";\n"
    s += f"static {c_struct} {name}_result[{M}] __attribute__((section(\".data\"))) = " + complex_tensor_to_cstr(result) + ";\n"
    return s

def main():
    parser = argparse.ArgumentParser(description="Generate data for dp-caxpy (CAXPY)")
    parser.add_argument("-c", "--cfg", type=pathlib.Path, required=True, help="Config .hjson (e.g. caxpy.hjson)")
    args = parser.parse_args()
    with args.cfg.open() as f:
        param = hjson.loads(f.read())
    assert param.get("kernel") == "CAXPY", "Config kernel must be CAXPY"
    M = param["M"]
    prec = param["prec"]
    dtype = torch.float64 if prec == 64 else torch.float32
    X = rand_complex((M,), dtype)
    Y = rand_complex((M,), dtype)
    alpha = rand_complex((1,), dtype)
    result = alpha * X + Y
    emit_str = "// Generated by gen_data.py (dp-caxpy)\n" + emit_caxpy("caxpy", M=M, prec=prec, X=X, Y=Y, alpha=alpha, result=result)
    outfile = f"data_{M}.h"
    out_path = pathlib.Path(__file__).parent.parent / "data" / outfile
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        f.write(emit_str)
    print(f"Generated {out_path}")

if __name__ == "__main__":
    main()
