// Copyright 2026 ETH Zurich and University of Bologna.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51

// Shared positive binary16 divider for mixed normalization.  The quotient is
// generated by a restoring 11-bit-significand divider with 24 fractional
// iterations; the final rounding uses the saved integer remainder, so this is
// a true binary16 divide rather than a reciprocal multiply followed by a
// storage cast.  Zero, normal and subnormal outputs are supported.
module online_merge_fp16_divider (
  input  logic                                clk_i,
  input  logic                                rst_ni,
  input  logic                                start_i,
  input  online_merge_fp32_helpers::fp16_bits_t numerator_i,
  input  online_merge_fp32_helpers::fp16_bits_t denominator_i,
  output logic                                busy_o,
  output logic                                done_o,
  output online_merge_fp32_helpers::fp16_bits_t result_o
);
  import online_merge_fp32_helpers::*;

  localparam int unsigned NUM_WIDTH = 35; // 11 significand + 24 fraction bits

  logic [NUM_WIDTH-1:0] work_q, quotient_q;
  logic [11:0] remainder_q, denominator_sig_q;
  logic signed [7:0] exponent_diff_q;
  logic sign_q;
  logic [5:0] iteration_q;
  logic busy_q, done_q;
  fp16_bits_t result_q;

  function automatic int signed div_subnormal_msb(input fp16_bits_t value);
    int signed msb;
    begin
      msb = 0;
      for (int i = 0; i < 10; i++) begin
        if (value[i]) begin
          msb = i;
        end
      end
      div_subnormal_msb = msb;
    end
  endfunction

  function automatic logic [10:0] div_significand(input fp16_bits_t value);
    int signed msb;
    begin
      if (value[14:10] == 0) begin
        // Normalize a subnormal before division.  Keeping the raw fraction
        // here would make every subnormal look like a 2^-24 value.
        msb = div_subnormal_msb(value);
        div_significand = {1'b0, value[9:0]} << (10 - msb);
      end else begin
        div_significand = {1'b1, value[9:0]};
      end
    end
  endfunction

  function automatic integer signed div_exponent(input fp16_bits_t value);
    if (value[14:10] == 0) begin
      // For a normalized subnormal sig*2^e representation, e is msb-34:
      // value = frac*2^-24 = (frac << (10-msb))*2^(msb-34).
      div_exponent = div_subnormal_msb(value) - 34;
    end else begin
      div_exponent = int'(value[14:10]) - 25;
    end
  endfunction

  function automatic logic [63:0] round_ratio(
    input logic [63:0] quotient,
    input logic [11:0] remainder,
    input logic [11:0] denominator,
    input int unsigned shift
  );
    logic [63:0] base;
    logic [63:0] discarded;
    logic [63:0] discarded_denominator;
    logic [63:0] mask;
    begin
      if (shift == 0) begin
        round_ratio = quotient;
      end else begin
        mask = (64'd1 << shift) - 64'd1;
        base = quotient >> shift;
        discarded = (quotient & mask) * {52'd0, denominator} +
            {52'd0, remainder};
        discarded_denominator = {52'd0, denominator} << shift;
        if ((discarded > (discarded_denominator >> 1)) ||
            ((discarded_denominator[0] == 1'b0) &&
             (discarded == (discarded_denominator >> 1)) && base[0]) ||
            ((discarded_denominator[0] == 1'b1) &&
             ((discarded << 1) == discarded_denominator) && base[0])) begin
          round_ratio = base + 64'd1;
        end else begin
          round_ratio = base;
        end
      end
    end
  endfunction

  function automatic fp16_bits_t finalize_divide(
    input logic [NUM_WIDTH-1:0] quotient,
    input logic [11:0] remainder,
    input logic [11:0] denominator,
    input logic signed [7:0] exponent_diff,
    input logic sign
  );
    logic [63:0] quotient_wide;
    logic [63:0] significand;
    logic [63:0] rounded;
    integer signed normalized_exponent;
    integer signed subnormal_shift;
    integer signed exponent_diff_int;
    begin
      quotient_wide = {{(64-NUM_WIDTH){1'b0}}, quotient};
      exponent_diff_int = int'($signed(exponent_diff));
      if (quotient_wide >= (64'd1 << 24)) begin
        significand = round_ratio(quotient_wide, remainder, denominator, 14);
        // quotient is a ratio of integer significands; a normalized
        // significand of 1024 represents 2^(e-10).
        normalized_exponent = exponent_diff_int - 10;
      end else begin
        significand = round_ratio(quotient_wide, remainder, denominator, 13);
        normalized_exponent = exponent_diff_int - 11;
      end
      if (significand >= 2048) begin
        significand = significand >> 1;
        normalized_exponent = normalized_exponent + 1;
      end
      if (normalized_exponent > 5) begin
        finalize_divide = {sign, 5'h1f, 10'd0};
      end else if (normalized_exponent >= -24) begin
        finalize_divide = {sign, 5'(normalized_exponent + 25),
                           significand[9:0]};
      end else begin
        // A half subnormal is an integer multiple of 2^-24.  quotient is
        // ratio * 2^24, hence divide it by 2^-exponent_diff before RNE.
        subnormal_shift = -exponent_diff_int;
        rounded = round_ratio(quotient_wide, remainder, denominator,
                              subnormal_shift);
        if (rounded >= 1024) begin
          finalize_divide = {sign, 5'd1, 10'd0};
        end else begin
          finalize_divide = {sign, 5'd0, rounded[9:0]};
        end
      end
    end
  endfunction

  assign busy_o = busy_q;
  assign done_o = done_q;
  assign result_o = result_q;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    logic [12:0] remainder_shift;
    logic quotient_bit;
    if (!rst_ni) begin
      work_q <= '0;
      quotient_q <= '0;
      remainder_q <= '0;
      denominator_sig_q <= '0;
      exponent_diff_q <= '0;
      sign_q <= 1'b0;
      iteration_q <= '0;
      busy_q <= 1'b0;
      done_q <= 1'b0;
      result_q <= FP16_POS_ZERO;
    end else begin
      done_q <= 1'b0;
      if (start_i && !busy_q) begin
        if (fp16_is_zero(numerator_i) || fp16_is_zero(denominator_i) ||
            fp16_is_nan_or_inf(numerator_i) ||
            fp16_is_nan_or_inf(denominator_i)) begin
          result_q <= FP16_POS_ZERO;
          done_q <= 1'b1;
          busy_q <= 1'b0;
        end else begin
          work_q <= {24'd0, div_significand(numerator_i)} << 24;
          quotient_q <= '0;
          remainder_q <= '0;
          denominator_sig_q <= {1'b0, div_significand(denominator_i)};
          exponent_diff_q <= 8'(div_exponent(numerator_i) -
              div_exponent(denominator_i));
          sign_q <= numerator_i[15] ^ denominator_i[15];
          iteration_q <= '0;
          busy_q <= 1'b1;
        end
      end else if (busy_q && (iteration_q < 6'd35)) begin
        remainder_shift = {remainder_q, work_q[NUM_WIDTH-1]};
        work_q <= work_q << 1;
        if (remainder_shift >= {1'b0, denominator_sig_q}) begin
          remainder_q <= remainder_shift[11:0] - denominator_sig_q;
          quotient_bit = 1'b1;
        end else begin
          remainder_q <= remainder_shift[11:0];
          quotient_bit = 1'b0;
        end
        quotient_q <= {quotient_q[NUM_WIDTH-2:0], quotient_bit};
        iteration_q <= iteration_q + 1'b1;
      end else if (busy_q) begin
        result_q <= finalize_divide(quotient_q, remainder_q,
                                    denominator_sig_q, exponent_diff_q,
                                    sign_q);
        busy_q <= 1'b0;
        done_q <= 1'b1;
      end
    end
  end
endmodule

// Cluster-local streaming update engine for online softmax merge state.
module online_merge_update_engine #(
  parameter int unsigned AddrWidth = 32,
  parameter int unsigned DataWidth = 64,
  // 0: legacy modes only, 1: mixed modes only, 2: dual runtime support.
  parameter int unsigned PrecisionSupport = 2,
  // Mixed normalization: 0 keeps the iterative FP16 divider baseline; 1
  // selects the reciprocal-LUT path and elaborates the divider away.
  parameter bit MixedNormalizationReciprocal = 1'b0,
  // Fixed scalar synthesis points can remove the vector-update datapath at
  // elaboration.  The default preserves the runtime mode behavior exactly.
  parameter bit ScalarOnly = 1'b0,
  parameter type tcdm_req_t = logic,
  parameter type tcdm_rsp_t = logic
) (
  input  logic                 clk_i,
  input  logic                 rst_ni,

  input  logic [AddrWidth-1:0] src_m_old_i,
  input  logic [AddrWidth-1:0] src_l_old_i,
  input  logic [AddrWidth-1:0] src_o_old_i,
  input  logic [AddrWidth-1:0] src_m_tile_i,
  input  logic [AddrWidth-1:0] src_l_tile_i,
  input  logic [AddrWidth-1:0] src_o_tile_i,
  input  logic [AddrWidth-1:0] dst_m_i,
  input  logic [AddrWidth-1:0] dst_l_i,
  input  logic [AddrWidth-1:0] dst_o_i,
  input  logic [AddrWidth-1:0] dst_weight_old_i,
  input  logic [AddrWidth-1:0] dst_weight_tile_i,
  input  logic [31:0]          n_i,
  input  logic [31:0]          d_i,
  input  logic [31:0]          stride_i,
  input  logic [31:0]          mode_i,
  input  logic                 start_i,
  input  logic                 clear_done_i,

  output logic                 busy_o,
  output logic                 done_o,
  output logic                 error_o,

  output tcdm_req_t            tcdm_req_o,
  input  tcdm_rsp_t            tcdm_rsp_i
);

  import online_merge_fp32_helpers::*;

  localparam int unsigned ByteWidth = DataWidth / 8;
  localparam bit SUPPORT_LEGACY = (PrecisionSupport != 1);
  localparam bit SUPPORT_MIXED = (PrecisionSupport != 0);
  localparam bit SUPPORT_MIXED_RECIP =
      SUPPORT_MIXED && MixedNormalizationReciprocal;
  typedef logic [AddrWidth-1:0] addr_t;
  typedef logic [DataWidth-1:0] data_t;
  typedef logic [ByteWidth-1:0] strb_t;

  typedef enum logic [2:0] {
    IDLE,
    LOAD_SCALAR,
    COMPUTE_SCALAR,
    COMPUTE_WEIGHT,
    STORE_SCALAR,
    UPDATE_VECTOR,
    DONE,
    ERROR
  } state_e;

  typedef enum logic [3:0] {
    RD_M_OLD,
    RD_L_OLD,
    RD_M_TILE,
    RD_L_TILE,
    WR_M_OUT,
    WR_L_OUT,
    WR_WEIGHT_OLD,
    WR_WEIGHT_TILE,
    RD_O_OLD,
    RD_O_TILE,
    WR_O_OUT
  } op_e;

  state_e state_q;
  logic done_q, error_q;
  logic [1:0] mode_q;
  logic use_mixed;
  logic req_valid_q, req_write_q, read_pending_q;
  addr_t req_addr_q;
  data_t req_wdata_q;
  strb_t req_strb_q;
  op_e op_q;

  logic [31:0] row_q, elem_q;
  logic [2:0] scalar_idx_q;
  logic [2:0] store_idx_q;
  logic [1:0] vector_idx_q;
  logic [31:0] m_old_q, l_old_q, m_tile_q, l_tile_q;
  logic [31:0] m_new_q, l_new_q, o_old_q, o_tile_q, o_new_q;
  uq16_16_t old_weight_q, tile_weight_q;
  fp16_bits_t old_weight_f16_q, tile_weight_f16_q;
  uq16_16_t l_new_fixed_q;
  logic [2:0] weight_phase_q;

  logic divider_start_q;
  fp16_bits_t divider_num_q, divider_den_q, divider_result;
  logic divider_busy, divider_done;

  q1_23_t old_exp_q1_23, tile_exp_q1_23, recip_q1_23;
  logic old_exp_valid, tile_exp_valid, recip_valid;
  logic old_exp_saturated, tile_exp_saturated;
  logic old_exp_unsupported, tile_exp_unsupported, recip_unsupported;
  logic signed [9:0] recip_scale_exp;
  fp32_bits_t old_exp_arg, tile_exp_arg, recip_input_bits, recip_input_q;
  q1_15_t mixed_recip_q1_15_q, mixed_recip_q1_15_d;
  logic signed [9:0] mixed_recip_scale_exp_q, mixed_recip_scale_exp_d;
  logic mixed_recip_valid_q, mixed_recip_valid_d;
  logic mixed_recip_unsupported_q, mixed_recip_unsupported_d;
  fp16_bits_t mixed_recip_den_h_d;
  fp32_bits_t mixed_recip_den_fp32_d;
  logic [7:0] mixed_recip_index_d;
  logic [14:0] mixed_recip_frac_d;
  q1_15_t mixed_recip_lut_lo_d, mixed_recip_lut_hi_d;
  logic [31:0] mixed_recip_interp_product_d;
  logic [15:0] mixed_recip_interp_step_d;
  uq16_16_t mixed_recip_selected_num_d;
  fp16_bits_t mixed_recip_num_h_d;
  uq16_16_t mixed_recip_num_q32_d;
  logic [63:0] mixed_recip_product_d, mixed_recip_shifted_d;
  logic signed [10:0] mixed_recip_net_shift_d;
  logic mixed_recip_overflow_d;
  fp16_bits_t mixed_recip_weight_h_d;
  uq16_16_t old_scaled_l_q, tile_scaled_l_q;
  fp32_bits_t m_new_d, l_new_d;
  uq16_16_t old_scaled_l_d, tile_scaled_l_d;
  uq16_16_t old_weight_d, tile_weight_d;
  fp32_bits_t m_new_comb;

  fp16_bits_t mixed_m_old_h, mixed_m_tile_h, mixed_m_new_h;
  logic mixed_old_is_loser, mixed_tile_is_loser;
  fp16_bits_t mixed_loser_h, mixed_winner_h;
  logic [7:0] mixed_loser_lut_index;
  logic [15:0] mixed_loser_exp_q1_14;
  logic mixed_loser_exp_valid, mixed_loser_exp_unsupported;
  logic [15:0] mixed_old_exp_q1_14, mixed_tile_exp_q1_14;
  logic mixed_old_exp_valid, mixed_tile_exp_valid;
  logic mixed_old_exp_unsupported, mixed_tile_exp_unsupported;
  fp32_bits_t mixed_m_new_d, mixed_l_new_d;
  uq16_16_t mixed_old_scaled_l_d, mixed_tile_scaled_l_d;
  uq16_16_t mixed_l_new_fixed_d;
  uq16_16_t mixed_old_weight_fixed, mixed_tile_weight_fixed;
  logic [48:0] mixed_l_new_sum_ext;
  fp16_bits_t mixed_l_new_h_d;
  logic mixed_merge_valid_d;

  assign m_new_comb = fp32_lt(m_old_q, m_tile_q) ? m_tile_q : m_old_q;
  assign old_exp_arg = sq16_16_to_fp32(
      fp32_to_sq16_16(m_old_q) - fp32_to_sq16_16(m_new_comb));
  assign tile_exp_arg = sq16_16_to_fp32(
      fp32_to_sq16_16(m_tile_q) - fp32_to_sq16_16(m_new_comb));
  assign recip_input_bits = recip_input_q;
  assign mixed_m_old_h = fp32_to_fp16_rne(m_old_q);
  assign mixed_m_tile_h = fp32_to_fp16_rne(m_tile_q);
  assign mixed_m_new_h = fp16_lt(mixed_m_old_h, mixed_m_tile_h) ?
      mixed_m_tile_h : mixed_m_old_h;
  assign mixed_old_is_loser = fp16_lt(mixed_m_old_h, mixed_m_tile_h);
  assign mixed_tile_is_loser = fp16_lt(mixed_m_tile_h, mixed_m_old_h);
  assign mixed_loser_h = mixed_old_is_loser ? mixed_m_old_h : mixed_m_tile_h;
  assign mixed_winner_h = mixed_old_is_loser ? mixed_m_tile_h : mixed_m_old_h;
  // There is one physical mixed LUT.  The winner is an exact identity and
  // equal converted maxima make both sides winners, so both factors bypass
  // the LUT with Q1.14 unity.
  assign mixed_old_exp_q1_14 = mixed_old_is_loser ? mixed_loser_exp_q1_14 :
      16'h4000;
  assign mixed_tile_exp_q1_14 = mixed_tile_is_loser ? mixed_loser_exp_q1_14 :
      16'h4000;
  assign mixed_old_exp_valid = mixed_loser_exp_valid;
  assign mixed_tile_exp_valid = mixed_loser_exp_valid;
  assign mixed_old_exp_unsupported = mixed_loser_exp_unsupported;
  assign mixed_tile_exp_unsupported = mixed_loser_exp_unsupported;
  assign mixed_old_weight_fixed = fp16_to_uq16_16(old_weight_f16_q);
  assign mixed_tile_weight_fixed = fp16_to_uq16_16(tile_weight_f16_q);
  assign mixed_recip_den_h_d = uq16_16_to_fp16(l_new_fixed_q);
  assign mixed_recip_den_fp32_d = fp16_to_fp32(mixed_recip_den_h_d);

  generate
    if (PrecisionSupport == 0) begin : gen_legacy_only
      assign use_mixed = 1'b0;
    end else if (PrecisionSupport == 1) begin : gen_mixed_only
      assign use_mixed = 1'b1;
    end else begin : gen_dual_precision
      assign use_mixed = mode_q[1];
    end

    if (SUPPORT_LEGACY) begin : gen_legacy_math
      online_merge_exp_approx i_old_exp_approx (
        .x_i             (old_exp_arg),
        .exp_q1_23_o     (old_exp_q1_23),
        .valid_o         (old_exp_valid),
        .saturated_o     (old_exp_saturated),
        .unsupported_o   (old_exp_unsupported)
      );

      online_merge_exp_approx i_tile_exp_approx (
        .x_i             (tile_exp_arg),
        .exp_q1_23_o     (tile_exp_q1_23),
        .valid_o         (tile_exp_valid),
        .saturated_o     (tile_exp_saturated),
        .unsupported_o   (tile_exp_unsupported)
      );

      online_merge_recip_approx i_recip_approx (
        .x_i             (recip_input_bits),
        .recip_q1_23_o   (recip_q1_23),
        .scale_exp_o     (recip_scale_exp),
        .valid_o         (recip_valid),
        .unsupported_o   (recip_unsupported)
      );
    end else begin : gen_no_legacy_math
      assign old_exp_q1_23 = '0;
      assign tile_exp_q1_23 = '0;
      assign old_exp_valid = 1'b0;
      assign tile_exp_valid = 1'b0;
      assign old_exp_saturated = 1'b0;
      assign tile_exp_saturated = 1'b0;
      assign old_exp_unsupported = 1'b1;
      assign tile_exp_unsupported = 1'b1;
      assign recip_q1_23 = '0;
      assign recip_scale_exp = '0;
      assign recip_valid = 1'b0;
      assign recip_unsupported = 1'b1;
    end

    if (SUPPORT_MIXED) begin : gen_mixed_math
      online_merge_fp16_delta_exp i_mixed_exp_loser (
        .loser_i         (mixed_loser_h),
        .winner_i        (mixed_winner_h),
        .address_o       (mixed_loser_lut_index),
        .exp_q1_14_o     (mixed_loser_exp_q1_14),
        .valid_o         (mixed_loser_exp_valid),
        .saturated_o     (),
        .unsupported_o   (mixed_loser_exp_unsupported)
      );

      if (MixedNormalizationReciprocal) begin : gen_mixed_reciprocal
        online_merge_recip_approx_q1_15 i_reciprocal_q1_15 (
          .x_i             (mixed_recip_den_fp32_d),
          .recip_q1_15_o   (mixed_recip_q1_15_d),
          .scale_exp_o     (mixed_recip_scale_exp_d),
          .valid_o         (mixed_recip_valid_d),
          .unsupported_o   (mixed_recip_unsupported_d),
          .index_o         (mixed_recip_index_d),
          .frac_o          (mixed_recip_frac_d),
          .lut_lo_o        (mixed_recip_lut_lo_d),
          .lut_hi_o        (mixed_recip_lut_hi_d),
          .interp_product_o(mixed_recip_interp_product_d),
          .interp_step_o   (mixed_recip_interp_step_d)
        );
        assign divider_busy = 1'b0;
        assign divider_done = 1'b0;
        assign divider_result = FP16_POS_ZERO;
      end else begin : gen_mixed_division
        online_merge_fp16_divider i_weight_divider (
          .clk_i         (clk_i),
          .rst_ni        (rst_ni),
          .start_i       (divider_start_q),
          .numerator_i   (divider_num_q),
          .denominator_i (divider_den_q),
          .busy_o        (divider_busy),
          .done_o        (divider_done),
          .result_o      (divider_result)
        );
        assign mixed_recip_q1_15_d = Q1_15_ZERO;
        assign mixed_recip_scale_exp_d = '0;
        assign mixed_recip_valid_d = 1'b0;
        assign mixed_recip_unsupported_d = 1'b1;
        assign mixed_recip_index_d = '0;
        assign mixed_recip_frac_d = '0;
        assign mixed_recip_lut_lo_d = Q1_15_ZERO;
        assign mixed_recip_lut_hi_d = Q1_15_ZERO;
        assign mixed_recip_interp_product_d = '0;
        assign mixed_recip_interp_step_d = '0;
      end
    end else begin : gen_no_mixed_math
      assign mixed_loser_exp_q1_14 = '0;
      assign mixed_loser_exp_valid = 1'b0;
      assign mixed_loser_exp_unsupported = 1'b1;
      assign divider_busy = 1'b0;
      assign divider_done = 1'b0;
      assign divider_result = FP16_POS_ZERO;
      assign mixed_recip_q1_15_d = Q1_15_ZERO;
      assign mixed_recip_scale_exp_d = '0;
      assign mixed_recip_valid_d = 1'b0;
      assign mixed_recip_unsupported_d = 1'b1;
      assign mixed_recip_index_d = '0;
      assign mixed_recip_frac_d = '0;
      assign mixed_recip_lut_lo_d = Q1_15_ZERO;
      assign mixed_recip_lut_hi_d = Q1_15_ZERO;
      assign mixed_recip_interp_product_d = '0;
      assign mixed_recip_interp_step_d = '0;
    end
  endgenerate

  // Reciprocal normalization uses one shared 48x16 unsigned multiplier.  A
  // single selected numerator is multiplied in each of the old/tile phases;
  // the exponent correction is applied once to the 64-bit product.
  generate
    if (SUPPORT_MIXED_RECIP) begin : gen_reciprocal_datapath
      always_comb begin
        mixed_recip_selected_num_d =
            (weight_phase_q == 3'd1) ? old_scaled_l_q : tile_scaled_l_q;
        // Match the divider contract: numerator is widened through FP16
        // before the shared 48x16 multiply, so both normalization paths use
        // the same RNE numerator quantization.
        mixed_recip_num_h_d = uq16_16_to_fp16(mixed_recip_selected_num_d);
        mixed_recip_num_q32_d = fp16_to_uq16_16(mixed_recip_num_h_d);
        mixed_recip_product_d =
            {16'd0, mixed_recip_num_q32_d} *
            {48'd0, mixed_recip_q1_15_q};
        mixed_recip_net_shift_d = 11'sd15 - $signed({
            mixed_recip_scale_exp_q[9], mixed_recip_scale_exp_q});
        if (mixed_recip_net_shift_d >= 0) begin
          mixed_recip_shifted_d = mixed_recip_product_d >>
              mixed_recip_net_shift_d;
        end else begin
          mixed_recip_shifted_d = mixed_recip_product_d <<
              (-mixed_recip_net_shift_d);
        end
        mixed_recip_overflow_d = |mixed_recip_shifted_d[63:48];
        if (mixed_recip_overflow_d) begin
          mixed_recip_weight_h_d = FP16_POS_ZERO;
        end else begin
          mixed_recip_weight_h_d = uq16_16_to_fp16(
              mixed_recip_shifted_d[47:0]);
        end
      end
    end else begin : gen_no_reciprocal_datapath
      assign mixed_recip_selected_num_d = '0;
      assign mixed_recip_num_h_d = FP16_POS_ZERO;
      assign mixed_recip_num_q32_d = '0;
      assign mixed_recip_product_d = '0;
      assign mixed_recip_shifted_d = '0;
      assign mixed_recip_net_shift_d = '0;
      assign mixed_recip_overflow_d = 1'b0;
      assign mixed_recip_weight_h_d = FP16_POS_ZERO;
    end
  endgenerate

  function automatic logic [31:0] pick_fp32(input data_t data, input addr_t addr);
    pick_fp32 = addr[2] ? data[63:32] : data[31:0];
  endfunction

  function automatic data_t pack_fp32(input logic [31:0] value, input addr_t addr);
    pack_fp32 = '0;
    if (addr[2]) begin
      pack_fp32[63:32] = value;
    end else begin
      pack_fp32[31:0] = value;
    end
  endfunction

  function automatic strb_t fp32_strb(input addr_t addr);
    fp32_strb = addr[2] ? strb_t'(8'hf0) : strb_t'(8'h0f);
  endfunction

  function automatic addr_t scalar_addr(input addr_t base, input logic [31:0] row);
    scalar_addr = base + addr_t'(row << 2);
  endfunction

  function automatic addr_t vector_addr(
    input addr_t base,
    input logic [31:0] row,
    input logic [31:0] elem,
    input logic [31:0] stride,
    input logic [31:0] d
  );
    logic [31:0] eff_stride;
    eff_stride = (stride == 32'd0) ? (d << 2) : stride;
    vector_addr = base + addr_t'(row * eff_stride) + addr_t'(elem << 2);
  endfunction

  function automatic logic is_aligned(input addr_t addr);
    is_aligned = (addr[1:0] == 2'b00);
  endfunction

  function automatic logic valid_cfg;
    logic stride_aligned;
    logic scalar_only;
    logic valid_mode;
    begin
      if (PrecisionSupport == 0) begin
        valid_mode = (mode_i <= 32'd1);
      end else if (PrecisionSupport == 1) begin
        valid_mode = (mode_i >= 32'd2) && (mode_i <= 32'd3);
      end else begin
        valid_mode = (mode_i <= 32'd3);
      end
      scalar_only = mode_i[0];
      stride_aligned = (stride_i == 32'd0) || (stride_i[1:0] == 2'b00);
      valid_cfg = valid_mode &&
          (n_i != 32'd0) && (d_i != 32'd0) && stride_aligned &&
          is_aligned(src_m_old_i) && is_aligned(src_l_old_i) &&
          is_aligned(src_o_old_i) && is_aligned(src_m_tile_i) &&
          is_aligned(src_l_tile_i) && is_aligned(src_o_tile_i) &&
          is_aligned(dst_m_i) && is_aligned(dst_l_i) && is_aligned(dst_o_i) &&
          (!scalar_only || (is_aligned(dst_weight_old_i) &&
                            is_aligned(dst_weight_tile_i)));
    end
  endfunction

  function automatic logic fp32_lt(input logic [31:0] lhs, input logic [31:0] rhs);
    logic lhs_sign, rhs_sign;
    begin
      lhs_sign = lhs[31];
      rhs_sign = rhs[31];
      if (lhs == rhs) begin
        fp32_lt = 1'b0;
      end else if (lhs_sign != rhs_sign) begin
        fp32_lt = lhs_sign;
      end else if (lhs_sign) begin
        fp32_lt = lhs > rhs;
      end else begin
        fp32_lt = lhs < rhs;
      end
    end
  endfunction

  function automatic logic supported_scalar_merge(
    input logic [31:0] m_old_bits,
    input logic [31:0] l_old_bits,
    input logic [31:0] m_tile_bits,
    input logic [31:0] l_tile_bits
  );
    begin
      supported_scalar_merge =
          fp32_is_finite_normal_or_zero(m_old_bits) &&
          fp32_is_finite_normal_or_zero(m_tile_bits) &&
          fp32_is_nonnegative_finite_normal_or_zero(l_old_bits) &&
          fp32_is_nonnegative_finite_normal_or_zero(l_tile_bits) &&
          !((l_old_bits == 32'd0) && (l_tile_bits == 32'd0));
    end
  endfunction

  function automatic void compute_scalar_merge(
    input  logic [31:0] m_old_bits,
    input  logic [31:0] l_old_bits,
    input  logic [31:0] m_tile_bits,
    input  logic [31:0] l_tile_bits,
    output logic [31:0] m_new_bits,
    output logic [31:0] l_new_bits,
    output uq16_16_t    old_scaled_l,
    output uq16_16_t    tile_scaled_l
  );
    uq16_16_t old_l;
    uq16_16_t tile_l;
    uq16_16_t l_new_fixed;
    begin
      m_new_bits = fp32_lt(m_old_bits, m_tile_bits) ? m_tile_bits : m_old_bits;
      old_l = fp32_abs_to_uq16_16(l_old_bits);
      tile_l = fp32_abs_to_uq16_16(l_tile_bits);
      old_scaled_l = q1_23_mul_uq16_16(old_l, old_exp_q1_23);
      tile_scaled_l = q1_23_mul_uq16_16(tile_l, tile_exp_q1_23);
      l_new_fixed = old_scaled_l + tile_scaled_l;
      l_new_bits = uq16_16_to_fp32(l_new_fixed);
    end
  endfunction

  function automatic void compute_mixed_scalar_merge(
    input  logic [31:0] m_old_bits,
    input  logic [31:0] l_old_bits,
    input  logic [31:0] m_tile_bits,
    input  logic [31:0] l_tile_bits,
    output logic [31:0] m_new_bits,
    output logic [31:0] l_new_bits,
    output uq16_16_t    old_scaled_l,
    output uq16_16_t    tile_scaled_l,
    output uq16_16_t    l_new_fixed
  );
    uq16_16_t old_l;
    uq16_16_t tile_l;
    begin
      m_new_bits = fp16_to_fp32(mixed_m_new_h);
      old_l = fp32_abs_to_uq16_16(l_old_bits);
      tile_l = fp32_abs_to_uq16_16(l_tile_bits);
      old_scaled_l = q1_23_mul_uq16_16(
          old_l, q1_14_to_q1_23(mixed_old_exp_q1_14));
      tile_scaled_l = q1_23_mul_uq16_16(
          tile_l, q1_14_to_q1_23(mixed_tile_exp_q1_14));
      l_new_fixed = old_scaled_l + tile_scaled_l;
      l_new_bits = uq16_16_to_fp32(l_new_fixed);
    end
  endfunction

  function automatic void compute_weights(
    input  uq16_16_t old_scaled_l,
    input  uq16_16_t tile_scaled_l,
    output uq16_16_t old_weight,
    output uq16_16_t tile_weight
  );
    begin
      old_weight = q1_23_scaled_mul_uq16_16(old_scaled_l, recip_q1_23, recip_scale_exp);
      tile_weight = q1_23_scaled_mul_uq16_16(tile_scaled_l, recip_q1_23, recip_scale_exp);
    end
  endfunction

  function automatic logic [31:0] compute_vector_merge(
    input logic [31:0] o_old_bits,
    input logic [31:0] o_tile_bits,
    input uq16_16_t old_weight,
    input uq16_16_t tile_weight
  );
    sq16_16_t old_term;
    sq16_16_t tile_term;
    sq16_16_t sum;
    begin
      old_term = sq16_16_mul_weight(fp32_to_sq16_16(o_old_bits), old_weight);
      tile_term = sq16_16_mul_weight(fp32_to_sq16_16(o_tile_bits), tile_weight);
      sum = old_term + tile_term;
      compute_vector_merge = sq16_16_to_fp32(sum);
    end
  endfunction

  function automatic addr_t scalar_read_addr(input logic [2:0] idx);
    unique case (idx)
      3'd0: scalar_read_addr = scalar_addr(src_m_old_i, row_q);
      3'd1: scalar_read_addr = scalar_addr(src_l_old_i, row_q);
      3'd2: scalar_read_addr = scalar_addr(src_m_tile_i, row_q);
      default: scalar_read_addr = scalar_addr(src_l_tile_i, row_q);
    endcase
  endfunction

  function automatic op_e scalar_read_op(input logic [2:0] idx);
    unique case (idx)
      3'd0: scalar_read_op = RD_M_OLD;
      3'd1: scalar_read_op = RD_L_OLD;
      3'd2: scalar_read_op = RD_M_TILE;
      default: scalar_read_op = RD_L_TILE;
    endcase
  endfunction

  always_comb begin
    compute_scalar_merge(m_old_q, l_old_q, m_tile_q, l_tile_q, m_new_d,
                         l_new_d, old_scaled_l_d, tile_scaled_l_d);
    compute_mixed_scalar_merge(m_old_q, l_old_q, m_tile_q, l_tile_q,
                               mixed_m_new_d, mixed_l_new_d,
                               mixed_old_scaled_l_d,
                               mixed_tile_scaled_l_d,
                               mixed_l_new_fixed_d);
    mixed_l_new_sum_ext = {1'b0, mixed_old_scaled_l_d} +
        {1'b0, mixed_tile_scaled_l_d};
    mixed_l_new_h_d = uq16_16_to_fp16(mixed_l_new_fixed_d);
    mixed_merge_valid_d = mixed_old_exp_valid && mixed_tile_exp_valid &&
        !mixed_old_exp_unsupported && !mixed_tile_exp_unsupported &&
        fp16_is_finite(mixed_m_old_h) && fp16_is_finite(mixed_m_tile_h) &&
        fp16_is_finite(mixed_m_new_h) &&
        fp32_fits_uq16_16(l_old_q) && fp32_fits_uq16_16(l_tile_q) &&
        !mixed_l_new_sum_ext[48] && (mixed_l_new_fixed_d != '0) &&
        fp16_is_finite(mixed_l_new_h_d) &&
        !fp16_is_zero(mixed_l_new_h_d);
    compute_weights(old_scaled_l_q, tile_scaled_l_q, old_weight_d,
                    tile_weight_d);
  end

  always_comb begin
    tcdm_req_o = '0;
    tcdm_req_o.q_valid = req_valid_q;
    tcdm_req_o.q.addr = req_addr_q;
    tcdm_req_o.q.write = req_write_q;
    tcdm_req_o.q.amo = reqrsp_pkg::AMONone;
    tcdm_req_o.q.data = req_wdata_q;
    tcdm_req_o.q.strb = req_strb_q;
    tcdm_req_o.q.user = '0;
  end

  assign busy_o = (state_q != IDLE) && (state_q != DONE) && (state_q != ERROR);
  assign done_o = done_q;
  assign error_o = error_q;

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      state_q <= IDLE;
      done_q <= 1'b0;
      error_q <= 1'b0;
      mode_q <= 2'd0;
      req_valid_q <= 1'b0;
      req_write_q <= 1'b0;
      read_pending_q <= 1'b0;
      req_addr_q <= '0;
      req_wdata_q <= '0;
      req_strb_q <= '0;
      op_q <= RD_M_OLD;
      row_q <= '0;
      elem_q <= '0;
      scalar_idx_q <= '0;
      store_idx_q <= '0;
      vector_idx_q <= '0;
      m_old_q <= '0;
      l_old_q <= '0;
      m_tile_q <= '0;
      l_tile_q <= '0;
      m_new_q <= '0;
      l_new_q <= '0;
      recip_input_q <= '0;
      o_old_q <= '0;
      o_tile_q <= '0;
      o_new_q <= '0;
      old_weight_q <= '0;
      tile_weight_q <= '0;
      old_weight_f16_q <= FP16_POS_ZERO;
      tile_weight_f16_q <= FP16_POS_ZERO;
      l_new_fixed_q <= '0;
      old_scaled_l_q <= '0;
      tile_scaled_l_q <= '0;
      weight_phase_q <= '0;
      divider_start_q <= 1'b0;
      divider_num_q <= FP16_POS_ZERO;
      divider_den_q <= FP16_POS_ZERO;
      mixed_recip_q1_15_q <= Q1_15_ZERO;
      mixed_recip_scale_exp_q <= '0;
      mixed_recip_valid_q <= 1'b0;
      mixed_recip_unsupported_q <= 1'b1;
    end else begin
      // Divider start is a one-cycle request generated by COMPUTE_WEIGHT.
      divider_start_q <= 1'b0;
      if (clear_done_i) begin
        done_q <= 1'b0;
        error_q <= 1'b0;
        if ((state_q == DONE) || (state_q == ERROR)) begin
          state_q <= IDLE;
        end
      end

      if (req_valid_q && tcdm_rsp_i.q_ready) begin
        req_valid_q <= 1'b0;
        if (!req_write_q) begin
          read_pending_q <= 1'b1;
        end
      end

      if (read_pending_q && tcdm_rsp_i.p_valid) begin
        read_pending_q <= 1'b0;
        unique case (op_q)
          RD_M_OLD:  m_old_q <= pick_fp32(tcdm_rsp_i.p.data, req_addr_q);
          RD_L_OLD:  l_old_q <= pick_fp32(tcdm_rsp_i.p.data, req_addr_q);
          RD_M_TILE: m_tile_q <= pick_fp32(tcdm_rsp_i.p.data, req_addr_q);
          RD_L_TILE: l_tile_q <= pick_fp32(tcdm_rsp_i.p.data, req_addr_q);
          RD_O_OLD:  if (!ScalarOnly)
                       o_old_q <= pick_fp32(tcdm_rsp_i.p.data, req_addr_q);
          RD_O_TILE: if (!ScalarOnly)
                       o_tile_q <= pick_fp32(tcdm_rsp_i.p.data, req_addr_q);
          default: ;
        endcase
      end

      unique case (state_q)
        IDLE: begin
          if (start_i) begin
            done_q <= 1'b0;
            error_q <= 1'b0;
            row_q <= '0;
            elem_q <= '0;
            scalar_idx_q <= '0;
            store_idx_q <= '0;
            vector_idx_q <= '0;
            if (valid_cfg()) begin
              mode_q <= mode_i[1:0];
              state_q <= LOAD_SCALAR;
            end else begin
              error_q <= 1'b1;
              state_q <= ERROR;
            end
          end
        end

        LOAD_SCALAR: begin
          if (!req_valid_q && !read_pending_q && (scalar_idx_q < 3'd4)) begin
            req_valid_q <= 1'b1;
            req_write_q <= 1'b0;
            req_addr_q <= scalar_read_addr(scalar_idx_q);
            req_wdata_q <= '0;
            req_strb_q <= '0;
            op_q <= scalar_read_op(scalar_idx_q);
          end else if (!req_valid_q && !read_pending_q && (scalar_idx_q == 3'd4)) begin
            scalar_idx_q <= '0;
            state_q <= COMPUTE_SCALAR;
          end
          if (read_pending_q && tcdm_rsp_i.p_valid) begin
            scalar_idx_q <= scalar_idx_q + 3'd1;
          end
        end

        COMPUTE_SCALAR: begin
          if (supported_scalar_merge(m_old_q, l_old_q, m_tile_q, l_tile_q)) begin
          if (use_mixed) begin
              if (mixed_merge_valid_d) begin
                m_new_q <= mixed_m_new_d;
                l_new_q <= mixed_l_new_d;
                l_new_fixed_q <= mixed_l_new_fixed_d;
                old_scaled_l_q <= mixed_old_scaled_l_d;
                tile_scaled_l_q <= mixed_tile_scaled_l_d;
                weight_phase_q <= 3'd0;
                state_q <= COMPUTE_WEIGHT;
              end else begin
                error_q <= 1'b1;
                state_q <= ERROR;
              end
            end else begin
              if (old_exp_valid && tile_exp_valid && !old_exp_unsupported &&
                  !tile_exp_unsupported) begin
                m_new_q <= m_new_d;
                l_new_q <= l_new_d;
                recip_input_q <= l_new_d;
                old_scaled_l_q <= old_scaled_l_d;
                tile_scaled_l_q <= tile_scaled_l_d;
                state_q <= COMPUTE_WEIGHT;
              end else begin
                error_q <= 1'b1;
                state_q <= ERROR;
              end
            end
          end else begin
            error_q <= 1'b1;
            state_q <= ERROR;
          end
        end

        COMPUTE_WEIGHT: begin
          if (use_mixed) begin
            if (MixedNormalizationReciprocal) begin
              unique case (weight_phase_q)
                3'd0: begin
                  if (mixed_recip_valid_d && !mixed_recip_unsupported_d) begin
                    mixed_recip_q1_15_q <= mixed_recip_q1_15_d;
                    mixed_recip_scale_exp_q <= mixed_recip_scale_exp_d;
                    mixed_recip_valid_q <= 1'b1;
                    mixed_recip_unsupported_q <= 1'b0;
                    weight_phase_q <= 3'd1;
                  end else begin
                    error_q <= 1'b1;
                    state_q <= ERROR;
                  end
                end
                3'd1: begin
                  if (mixed_recip_overflow_d) begin
                    error_q <= 1'b1;
                    state_q <= ERROR;
                  end else begin
                    old_weight_f16_q <= mixed_recip_weight_h_d;
                    weight_phase_q <= 3'd2;
                  end
                end
                default: begin
                  if (mixed_recip_overflow_d || !mixed_recip_valid_q ||
                      mixed_recip_unsupported_q) begin
                    error_q <= 1'b1;
                    state_q <= ERROR;
                  end else begin
                    tile_weight_f16_q <= mixed_recip_weight_h_d;
                    store_idx_q <= '0;
                    state_q <= STORE_SCALAR;
                  end
                end
              endcase
            end else begin
              unique case (weight_phase_q)
                3'd0: begin
                  if (!divider_busy) begin
                    divider_num_q <= uq16_16_to_fp16(old_scaled_l_q);
                    divider_den_q <= uq16_16_to_fp16(l_new_fixed_q);
                    divider_start_q <= 1'b1;
                    weight_phase_q <= 3'd1;
                  end
                end
                3'd1: begin
                  if (divider_done) begin
                    old_weight_f16_q <= divider_result;
                    weight_phase_q <= 3'd2;
                  end
                end
                3'd2: begin
                  if (!divider_busy) begin
                    divider_num_q <= uq16_16_to_fp16(tile_scaled_l_q);
                    divider_den_q <= uq16_16_to_fp16(l_new_fixed_q);
                    divider_start_q <= 1'b1;
                    weight_phase_q <= 3'd3;
                  end
                end
                default: begin
                  if (divider_done) begin
                    tile_weight_f16_q <= divider_result;
                    store_idx_q <= '0;
                    state_q <= STORE_SCALAR;
                  end
                end
              endcase
            end
          end else begin
            if (recip_valid && !recip_unsupported) begin
              old_weight_q <= old_weight_d;
              tile_weight_q <= tile_weight_d;
              store_idx_q <= '0;
              state_q <= STORE_SCALAR;
            end else begin
              error_q <= 1'b1;
              state_q <= ERROR;
            end
          end
        end

        STORE_SCALAR: begin
          if (!req_valid_q && !read_pending_q &&
              (store_idx_q <
               (ScalarOnly ? 3'd4 : (mode_q[0] ? 3'd4 : 3'd2)))) begin
            req_valid_q <= 1'b1;
            req_write_q <= 1'b1;
            unique case (store_idx_q)
              3'd0: begin
                req_addr_q <= scalar_addr(dst_m_i, row_q);
                req_wdata_q <= pack_fp32(m_new_q,
                                         scalar_addr(dst_m_i, row_q));
                req_strb_q <= fp32_strb(scalar_addr(dst_m_i, row_q));
                op_q <= WR_M_OUT;
              end
              3'd1: begin
                req_addr_q <= scalar_addr(dst_l_i, row_q);
                req_wdata_q <= pack_fp32(l_new_q,
                                         scalar_addr(dst_l_i, row_q));
                req_strb_q <= fp32_strb(scalar_addr(dst_l_i, row_q));
                op_q <= WR_L_OUT;
              end
              3'd2: begin
                req_addr_q <= scalar_addr(dst_weight_old_i, row_q);
                req_wdata_q <= pack_fp32(use_mixed ?
                                         fp16_to_fp32(old_weight_f16_q) :
                                         uq16_16_to_fp32(old_weight_q),
                                         scalar_addr(dst_weight_old_i, row_q));
                req_strb_q <= fp32_strb(
                    scalar_addr(dst_weight_old_i, row_q));
                op_q <= WR_WEIGHT_OLD;
              end
              default: begin
                req_addr_q <= scalar_addr(dst_weight_tile_i, row_q);
                req_wdata_q <= pack_fp32(use_mixed ?
                                         fp16_to_fp32(tile_weight_f16_q) :
                                         uq16_16_to_fp32(tile_weight_q),
                                         scalar_addr(dst_weight_tile_i, row_q));
                req_strb_q <= fp32_strb(
                    scalar_addr(dst_weight_tile_i, row_q));
                op_q <= WR_WEIGHT_TILE;
              end
            endcase
          end else if (req_valid_q && tcdm_rsp_i.q_ready) begin
            store_idx_q <= store_idx_q + 3'd1;
          end else if (!req_valid_q && !read_pending_q &&
                       (store_idx_q ==
                        (ScalarOnly ? 3'd4 :
                         (mode_q[0] ? 3'd4 : 3'd2)))) begin
            if (ScalarOnly || mode_q[0]) begin
              if (row_q == (n_i - 32'd1)) begin
                done_q <= 1'b1;
                state_q <= DONE;
              end else begin
                row_q <= row_q + 32'd1;
                scalar_idx_q <= '0;
                store_idx_q <= '0;
                state_q <= LOAD_SCALAR;
              end
            end else begin
              elem_q <= '0;
              vector_idx_q <= '0;
              state_q <= UPDATE_VECTOR;
            end
          end
        end

        UPDATE_VECTOR: begin
          if (ScalarOnly) begin
            // A fixed scalar synthesis point cannot legally enter this state;
            // retain a safe recovery path while allowing synthesis to remove
            // the vector datapath and its O-state registers.
            error_q <= 1'b1;
            state_q <= ERROR;
          end else begin
            if (elem_q == d_i) begin
              if (row_q == (n_i - 32'd1)) begin
                done_q <= 1'b1;
                state_q <= DONE;
              end else begin
                row_q <= row_q + 32'd1;
                elem_q <= '0;
                scalar_idx_q <= '0;
                state_q <= LOAD_SCALAR;
              end
            end
            if (!req_valid_q && !read_pending_q && (elem_q != d_i)) begin
              unique case (vector_idx_q)
                2'd0: begin
                  req_valid_q <= 1'b1;
                  req_write_q <= 1'b0;
                  req_addr_q <= vector_addr(src_o_old_i, row_q, elem_q, stride_i, d_i);
                  req_wdata_q <= '0;
                  req_strb_q <= '0;
                  op_q <= RD_O_OLD;
                end
                2'd1: begin
                  req_valid_q <= 1'b1;
                  req_write_q <= 1'b0;
                  req_addr_q <= vector_addr(src_o_tile_i, row_q, elem_q, stride_i, d_i);
                  req_wdata_q <= '0;
                  req_strb_q <= '0;
                  op_q <= RD_O_TILE;
                end
                default: begin
                  o_new_q <= compute_vector_merge(o_old_q, o_tile_q,
                                                  use_mixed ?
                                                      mixed_old_weight_fixed :
                                                      old_weight_q,
                                                  use_mixed ?
                                                      mixed_tile_weight_fixed :
                                                      tile_weight_q);
                  req_valid_q <= 1'b1;
                  req_write_q <= 1'b1;
                  req_addr_q <= vector_addr(dst_o_i, row_q, elem_q, stride_i, d_i);
                  req_wdata_q <= pack_fp32(compute_vector_merge(
                                               o_old_q, o_tile_q,
                                               use_mixed ? mixed_old_weight_fixed :
                                                           old_weight_q,
                                               use_mixed ? mixed_tile_weight_fixed :
                                                           tile_weight_q),
                                           vector_addr(dst_o_i, row_q, elem_q, stride_i, d_i));
                  req_strb_q <= fp32_strb(vector_addr(dst_o_i, row_q, elem_q, stride_i, d_i));
                  op_q <= WR_O_OUT;
                end
              endcase
            end

            if (read_pending_q && tcdm_rsp_i.p_valid) begin
              vector_idx_q <= vector_idx_q + 2'd1;
            end else if (req_valid_q && req_write_q &&
                         tcdm_rsp_i.q_ready && (op_q == WR_O_OUT)) begin
              vector_idx_q <= '0;
              elem_q <= elem_q + 32'd1;
            end
          end
        end

        DONE: begin
          if (start_i) begin
            done_q <= 1'b0;
            error_q <= 1'b0;
            row_q <= '0;
            elem_q <= '0;
            scalar_idx_q <= '0;
            store_idx_q <= '0;
            vector_idx_q <= '0;
            if (valid_cfg()) begin
              mode_q <= mode_i[1:0];
              state_q <= LOAD_SCALAR;
            end else begin
              error_q <= 1'b1;
              state_q <= ERROR;
            end
          end
        end

        ERROR: begin
          if (start_i) begin
            done_q <= 1'b0;
            error_q <= 1'b0;
            row_q <= '0;
            elem_q <= '0;
            scalar_idx_q <= '0;
            store_idx_q <= '0;
            vector_idx_q <= '0;
            if (valid_cfg()) begin
              mode_q <= mode_i[1:0];
              state_q <= LOAD_SCALAR;
            end else begin
              error_q <= 1'b1;
            end
          end
        end

        default: begin
          error_q <= 1'b1;
          state_q <= ERROR;
        end
      endcase
    end
  end

  // Simulation-only, non-intrusive FSM cycle observer.  The counters do not
  // feed functional logic and are omitted by synthesis.  One structured
  // record is emitted after each terminal transition; invocation zero is the
  // benchmark warm-up and later invocations are measured repeats.
  // pragma translate_off
  logic [63:0] sim_load_scalar_cycles_q;
  logic [63:0] sim_compute_scalar_cycles_q;
  logic [63:0] sim_compute_weight_cycles_q;
  logic [63:0] sim_store_scalar_cycles_q;
  logic [63:0] sim_update_vector_cycles_q;
  logic [63:0] sim_busy_cycles_q;
  logic [31:0] sim_invocation_q;
  logic [31:0] sim_n_q, sim_d_q;
  logic [1:0] sim_mode_q;
  logic sim_observing_q;

  initial begin
`ifdef SPATZ_DISABLE_DASM
    $write("OM_SIM_CONFIG {\"schema_version\":1,");
    $write("\"profile\":\"low_perturbation\",");
    $write("\"dasm_trace_enabled\":false,");
`else
    $write("OM_SIM_CONFIG {\"schema_version\":1,");
    $write("\"profile\":\"default\",");
    $write("\"dasm_trace_enabled\":true,");
`endif
    $display("\"fsm_observer_enabled\":true}");
  end

  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      sim_load_scalar_cycles_q <= '0;
      sim_compute_scalar_cycles_q <= '0;
      sim_compute_weight_cycles_q <= '0;
      sim_store_scalar_cycles_q <= '0;
      sim_update_vector_cycles_q <= '0;
      sim_busy_cycles_q <= '0;
      sim_invocation_q <= '0;
      sim_n_q <= '0;
      sim_d_q <= '0;
      sim_mode_q <= '0;
      sim_observing_q <= 1'b0;
    end else if (start_i &&
                 ((state_q == IDLE) || (state_q == DONE) ||
                  (state_q == ERROR))) begin
      sim_load_scalar_cycles_q <= '0;
      sim_compute_scalar_cycles_q <= '0;
      sim_compute_weight_cycles_q <= '0;
      sim_store_scalar_cycles_q <= '0;
      sim_update_vector_cycles_q <= '0;
      sim_busy_cycles_q <= '0;
      sim_n_q <= n_i;
      sim_d_q <= d_i;
      sim_mode_q <= mode_i[1:0];
      sim_observing_q <= 1'b1;
    end else if (sim_observing_q) begin
      unique case (state_q)
        LOAD_SCALAR: begin
          sim_load_scalar_cycles_q <= sim_load_scalar_cycles_q + 64'd1;
          sim_busy_cycles_q <= sim_busy_cycles_q + 64'd1;
        end
        COMPUTE_SCALAR: begin
          sim_compute_scalar_cycles_q <= sim_compute_scalar_cycles_q + 64'd1;
          sim_busy_cycles_q <= sim_busy_cycles_q + 64'd1;
        end
        COMPUTE_WEIGHT: begin
          sim_compute_weight_cycles_q <= sim_compute_weight_cycles_q + 64'd1;
          sim_busy_cycles_q <= sim_busy_cycles_q + 64'd1;
        end
        STORE_SCALAR: begin
          sim_store_scalar_cycles_q <= sim_store_scalar_cycles_q + 64'd1;
          sim_busy_cycles_q <= sim_busy_cycles_q + 64'd1;
        end
        UPDATE_VECTOR: begin
          sim_update_vector_cycles_q <= sim_update_vector_cycles_q + 64'd1;
          sim_busy_cycles_q <= sim_busy_cycles_q + 64'd1;
        end
        DONE, ERROR: begin
          $write("OM_FSM {\"schema_version\":1,");
          $write("\"invocation\":%0d,\"N\":%0d,\"D\":%0d,\"mode\":%0d,",
                 sim_invocation_q, sim_n_q, sim_d_q, sim_mode_q);
          if (state_q == DONE) begin
            $write("\"terminal_state\":\"DONE\",");
          end else begin
            $write("\"terminal_state\":\"ERROR\",");
          end
          $write("\"load_scalar_cycles\":%0d,",
                 sim_load_scalar_cycles_q);
          $write("\"compute_scalar_cycles\":%0d,",
                 sim_compute_scalar_cycles_q);
          $write("\"compute_weight_cycles\":%0d,",
                 sim_compute_weight_cycles_q);
          $write("\"store_scalar_cycles\":%0d,",
                 sim_store_scalar_cycles_q);
          $write("\"update_vector_cycles\":%0d,",
                 sim_update_vector_cycles_q);
          $display("\"busy_cycles\":%0d}", sim_busy_cycles_q);
          sim_invocation_q <= sim_invocation_q + 32'd1;
          sim_observing_q <= 1'b0;
        end
        default: ;
      endcase
    end
  end
  // pragma translate_on

endmodule
