#!/usr/bin/env python3
# Generate data for widening-bp-cmatmul (cbyte: char real, char imag). Outputs to ../data.

import numpy as np
import argparse
import pathlib
import hjson

np.random.seed(42)

def cbyte_to_cstr(real_arr, imag_arr):
    """Emit C initializer for cbyte arrays: {r0,i0,r1,i1,...} with values in [-128,127]."""
    out = "{"
    r = np.clip(np.round(real_arr).astype(np.int32), -128, 127)
    i = np.clip(np.round(imag_arr).astype(np.int32), -128, 127)
    for re, im in zip(r.flat, i.flat):
        out += "{}, {}, ".format(int(re), int(im))
    return out[:-2] + "}"

def rand_complex_byte(shape, scale=10.0):
    real = np.clip(np.round(np.random.randn(*shape) * scale).astype(np.int32), -128, 127)
    imag = np.clip(np.round(np.random.randn(*shape) * scale).astype(np.int32), -128, 127)
    return real, imag

def emit_cmatmul(name, **kwargs):
    M, N, K = kwargs["M"], kwargs["N"], kwargs["K"]
    A_r, A_i = kwargs["A_r"], kwargs["A_i"]
    B_r, B_i = kwargs["B_r"], kwargs["B_i"]
    C_r, C_i = kwargs["C_r"], kwargs["C_i"]
    R_r, R_i = kwargs["result_r"], kwargs["result_i"]
    s = '#include "layer.h"\n\n'
    s += f"const int {name}_M = {M};\n"
    s += f"const int {name}_N = {K};\n"
    s += f"const int {name}_P = {N};\n\n"
    s += f"static cbyte {name}_a[{M}*{K}] __attribute__((section(\".data\"))) = " + cbyte_to_cstr(A_r, A_i) + ";\n"
    s += f"static cbyte {name}_b[{K}*{N}] __attribute__((section(\".data\"))) = " + cbyte_to_cstr(B_r, B_i) + ";\n"
    s += f"static cbyte {name}_c[{M}*{N}] __attribute__((section(\".data\"))) = " + cbyte_to_cstr(C_r, C_i) + ";\n"
    s += f"static cbyte {name}_result[{M}*{N}] __attribute__((section(\".data\"))) = " + cbyte_to_cstr(R_r, R_i) + ";\n"
    return s

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--cfg", type=pathlib.Path, required=True)
    args = parser.parse_args()
    with args.cfg.open() as f:
        param = hjson.loads(f.read())
    M, N, K = param["M"], param["N"], param["K"]
    scale = 5.0
    A_r, A_i = rand_complex_byte((M, K), scale)
    B_r, B_i = rand_complex_byte((K, N), scale)
    C_r, C_i = rand_complex_byte((M, N), scale)
    # Golden: C + A*B (complex matmul with integer components)
    # (A_r + i*A_i)*(B_r + i*B_i) = (A_r*B_r - A_i*B_i) + i*(A_r*B_i + A_i*B_r)
    AB_r = np.dot(A_r, B_r) - np.dot(A_i, B_i)
    AB_i = np.dot(A_r, B_i) + np.dot(A_i, B_r)
    R_r = np.clip(AB_r + C_r, -128, 127)
    R_i = np.clip(AB_i + C_i, -128, 127)
    emit_str = "// Generated by gen_data.py (cbyte)\n" + emit_cmatmul("cmatmul",
        M=M, N=N, K=K,
        A_r=A_r, A_i=A_i, B_r=B_r, B_i=B_i, C_r=C_r, C_i=C_i,
        result_r=R_r, result_i=R_i)
    outfile = f"data_{M}_{N}_{K}.h"
    out_path = pathlib.Path(__file__).parent.parent / "data" / outfile
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        f.write(emit_str)
    print(f"Generated {outfile}")

if __name__ == "__main__":
    main()
