#!/usr/bin/env python3
# Generate data for hp-cmatmul (chalf, prec 16). Outputs to ../data.

import numpy as np
import torch
import argparse
import pathlib
import hjson

np.random.seed(42)
torch.manual_seed(42)

def array_to_cstr(a, fmt=float):
    out = "{"
    if isinstance(a, torch.Tensor):
        a = a.detach().cpu().numpy().flat
    elif isinstance(a, np.ndarray):
        a = a.flat
    for el in a:
        out += "{:.8f}, ".format(el) if fmt == float else "{}, ".format(el)
    return out[:-2] + "}"

def complex_tensor_to_cstr(t):
    if t.is_complex():
        flat = torch.view_as_real(t).flatten()
    else:
        flat = t.flatten()
    return array_to_cstr(flat, fmt=float)

def rand_complex(shape, dtype):
    return torch.complex(torch.randn(shape, dtype=dtype), torch.randn(shape, dtype=dtype))

def emit_cmatmul(name, **kwargs):
    M, N, K = kwargs["M"], kwargs["N"], kwargs["K"]
    prec = kwargs["prec"]
    A, B, C = kwargs["A"], kwargs["B"], kwargs["C"]
    result = kwargs["result"]
    s = '#include "layer.h"\n\n'
    s += f"// CMATMUL prec={prec}. A MxK, B KxN, C MxN.\n"
    s += f"const int {name}_M = {M};\n"
    s += f"const int {name}_N = {K};\n"
    s += f"const int {name}_P = {N};\n\n"
    s += f"static chalf {name}_a[{M}*{K}] __attribute__((section(\".data\"))) = " + complex_tensor_to_cstr(A) + ";\n"
    s += f"static chalf {name}_b[{K}*{N}] __attribute__((section(\".data\"))) = " + complex_tensor_to_cstr(B) + ";\n"
    s += f"static chalf {name}_c[{M}*{N}] __attribute__((section(\".data\"))) = " + complex_tensor_to_cstr(C) + ";\n"
    s += f"static chalf {name}_result[{M}*{N}] __attribute__((section(\".data\"))) = " + complex_tensor_to_cstr(result) + ";\n"
    return s

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--cfg", type=pathlib.Path, required=True)
    args = parser.parse_args()
    with args.cfg.open() as f:
        param = hjson.loads(f.read())
    M, N, K = param["M"], param["N"], param["K"]
    dtype = torch.float32
    A = rand_complex((M, K), dtype)
    B = rand_complex((K, N), dtype)
    C = rand_complex((M, N), dtype)
    result = C + torch.matmul(A, B)
    emit_str = "// Generated by gen_data.py\n" + emit_cmatmul("cmatmul", M=M, N=N, K=K, prec=16, A=A, B=B, C=C, result=result)
    outfile = f"data_{M}_{N}_{K}.h"
    out_path = pathlib.Path(__file__).parent.parent / "data" / outfile
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        f.write(emit_str)
    print(f"Generated {outfile}")

if __name__ == "__main__":
    main()
